---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
      #defaultZone: http://localhost:8010/eureka/

server:
  port: ${PORT:${SERVER_PORT:0}}

---
spring:
  profiles: sentence
  application:
    name: lab-3-eureka-client-sentence
server:
  port: 8020  
words: NotApplicable
    
---
spring:
  profiles: subject
  application:
    name: lab-3-eureka-client-subject
words: I,You,He,She,It
  
---
spring:
  profiles: verb
  application:
    name: lab-3-eureka-client-verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
  application:
    name: lab-3-eureka-client-article
words: a,the

---
spring:
  profiles: adjective
  application:
    name: lab-3-eureka-client-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  application:
    name: lab-3-eureka-client-noun
words: boat,book,vote,seat,backpack,partition,groundhog