---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/usamamali/springboot-microservices-labs
          search-paths: ConfigData/lab-3
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
      #defaultZone: http://localhost:8010/eureka/

server:
  port: 8005